[env:pro_micro_nrf52840]
platform = https://github.com/LeeorNahum/platform-n-able-pro-micro-nrf52840.git#master
board = pro_micro_nrf52840
framework = arduino

build_flags = 
  -DVARIANT_MCK=64000000ul
  -DUSE_TINYUSB
  -DUSBCON

lib_deps =
  Adafruit SSD1306
  Adafruit BME280 Library
  Adafruit Unified Sensor