#ifndef RSSI_CLASSIFIER_H
#define RSSI_CLASSIFIER_H

#include <Arduino.h>
#include <math.h>

// ============================================================
// Lightweight ML inference for RSSI-based relay decision
// Architecture: Dense(4->8, ReLU) -> Dense(8->4, ReLU) -> Dense(4->1, Sigmoid)
//
// Input:  [rssi, src, from, node]  (raw values)
// Output: probability (0.0-1.0), >=0.5 = should relay
//
// GENERATED by tools/train_model.py -- do not edit by hand.
//   dataset : rssi_log.csv
//   samples : 42 (relay 8 / no-relay 34)
//   accuracy: 97.6% on the training set
// ============================================================

// ---- Normalization constants (from training data) ----
// A std of 0 means the feature never varied while logging, so it carries no
// information; normalizeInput() forces it to 0 instead of amplifying the
// difference (a 1e-6 floor turned a one-off node id into +-1e6 and saturated
// every ReLU).
static const float ML_MEAN[4] = {
  -57.00000000f, +109.71428571f, +109.71428571f, +117.00000000f
};
static const float ML_STD[4]  = {
  +19.97260028f, +3.28260723f, +3.28260723f, +0.00000000f
};

// ---- Layer 1: Dense(4->8, ReLU) ----  W1 row-major [4][8]
static const float W1[32] = {
  +0.89703215f, -0.02465323f, +0.86427832f, -1.85232168f,
  +0.09943083f, +0.42101476f, +1.36500157f, +0.42489908f,
  -1.30838513f, -0.96465946f, -0.85370762f, -0.92734332f,
  -2.12415248f, -0.31897397f, -1.32491719f, -0.27313521f,
  -1.19561840f, -0.29352934f, -0.12191928f, -0.21939693f,
  -0.57099518f, +0.80197069f, -0.91428878f, +0.49321116f,
  +0.63884989f, +0.06647673f, -0.52573336f, -0.65175826f,
  -0.32366104f, +0.15570146f, -0.71390786f, -0.14790947f
};
static const float b1[8] = {
  +0.81077106f, +0.06987174f, +0.41298637f, -0.95656374f,
  +0.48010811f, -0.16426485f, +0.44392533f, -0.24465603f
};

// ---- Layer 2: Dense(8->4, ReLU) ----  W2 row-major [8][4]
static const float W2[32] = {
  -0.34719128f, +1.35321900f, -0.05953680f, +0.17768635f,
  -0.58502384f, +0.68629745f, +0.22504096f, +0.74671557f,
  -0.87831977f, +1.92111169f, +0.50712647f, +0.39065570f,
  +0.41777659f, -2.02711575f, +3.01694529f, +3.35664021f,
  +0.63868171f, +1.62573335f, +0.01140736f, -0.60415932f,
  +0.17580116f, +0.16533403f, -0.47333837f, +0.36698611f,
  -0.06403923f, +1.15928761f, -0.76061088f, -0.33085129f,
  -0.47240571f, -0.16446143f, +0.70287266f, -0.24795536f
};
static const float b2[4] = {
  -0.58033557f, +0.21219704f, -0.54557656f, -0.74659747f
};

// ---- Layer 3: Dense(4->1, Sigmoid) ----
static const float W3[4] = {
  -0.28897678f, -1.05636641f, +3.77361368f, +3.59778834f
};
static const float b3 = -0.70141238f;

// ============================================================
// normalizeInput — z-score, with degenerate features zeroed
// ============================================================
static inline void normalizeInput(float raw[4], float norm[4]) {
    for (int i = 0; i < 4; i++) {
        if (ML_STD[i] < 1e-6f) { norm[i] = 0.0f; continue; }  // constant in training
        norm[i] = (raw[i] - ML_MEAN[i]) / ML_STD[i];
    }
}

// ============================================================
// mlPredictRelay — full forward pass, returns probability 0.0-1.0
// ============================================================
static inline float mlPredictRelay(const float raw[4]) {
    float x[4];
    normalizeInput((float*)raw, x);

    float a1[8];
    for (int j = 0; j < 8; j++) {
        float z = b1[j];
        for (int i = 0; i < 4; i++) z += x[i] * W1[i * 8 + j];
        a1[j] = (z > 0) ? z : 0.0f;
    }

    float a2[4];
    for (int j = 0; j < 4; j++) {
        float z = b2[j];
        for (int i = 0; i < 8; i++) z += a1[i] * W2[i * 4 + j];
        a2[j] = (z > 0) ? z : 0.0f;
    }

    float z3 = b3;
    for (int i = 0; i < 4; i++) z3 += a2[i] * W3[i];
    return 1.0f / (1.0f + expf(-z3));
}

// ============================================================
// Convenience: predictRelay — true when prob >= 0.5
// ============================================================
static inline bool predictRelay(int16_t rssi, uint8_t src, uint8_t rhFrom, uint8_t nodeId) {
    float raw[4] = { (float)rssi, (float)src, (float)rhFrom, (float)nodeId };
    return mlPredictRelay(raw) >= 0.5f;
}

#endif // RSSI_CLASSIFIER_H
